// @generated by schema-rust from an authority-verified bootstrap Interface

pub enum z2VYMA {
    z2VZNT(signal_criome::schema::lib::z2VUph),
    z2VPNR,
    z2VRVX(signal_criome::schema::lib::z2VfEW),
    z2VVft,
}
pub enum z2VbRz {
    z2VSji(z2VTuM),
    z2VZ1e(z2VNJM),
    z2VPTa(z2VNoR),
    z2VQdY(z2VMEW),
    z2VdSS(signal_criome::schema::lib::z2VNo7),
    z2VRZk(z2VWEF),
    z2VPiG(signal_criome::schema::lib::z2VUjo),
    z2VVTE(signal_criome::schema::lib::z2VUjo),
    z2VLt9(signal_criome::schema::lib::z2VXWs),
    z2VPvP(z2VXeB),
    z2VSKi(z2VUap),
    z2Vccz(signal_criome::schema::lib::z2VSGX),
}
pub enum z2VV8c {z2VSFd , z2VVCD , z2VeU9 , z2Ve13 ,} 
pub struct z2VNJM {
    pub field_0: z2VTTd,
    pub field_1: z2VRQa,
}
pub struct z2VbSK {
    pub field_0: z2VMX8,
    pub field_1: z2VZJL,
    pub field_2: z2VKvm,
    pub field_3: z2VLa8,
}
pub struct z2VcUQ {
    pub field_0: z2VZJL,
    pub field_1: z2VWEF,
}
pub enum z2VLkg {z2VLAD , z2VM7H ,} 
pub enum z2VN7W {z2VPWo , z2VX7f , z2VUwy , z2VMZa , z2VRUU , z2VRMx ,} 
pub struct z2VKvm(std::string::String);
impl z2VKvm {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VP5n {z2Varm , z2VPMD ( z2VYh1 ,) ,} 
pub struct z2VTuM(std::string::String);
impl z2VTuM {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWZH(std::string::String);
impl z2VWZH {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VUap {
    pub field_0: z2VZJL,
    pub field_1: z2VLyc,
    pub field_2: z2VRQk,
}
pub struct z2VMX8(std::string::String);
impl z2VMX8 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VRQa {z2VYKc ( z2VPxB ,) , z2VRaK ( z2VYh1 ,) , z2VWWy ( z2VWEF ,) , z2VcUe ( z2VZJL ,) , z2VUCQ ( z2VMYt ,) , z2VTmX ( z2VL6F ,) ,} 
pub struct z2VTTd(std::string::String);
impl z2VTTd {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VZJL(std::string::String);
impl z2VZJL {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VLa8(u64);
impl z2VLa8 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VL6F(std::string::String);
impl z2VL6F {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VTVx {
    z2Vezf(z2VVds),
    z2VUvB(z2VN4g),
    z2VPmd(signal_criome::schema::lib::z2VW3f),
    z2VQQe(z2VfCM),
    z2VbGs(z2VbSK),
    z2VLQ9(z2Vdss),
    z2VdDM(signal_criome::schema::lib::z2VRAT),
    z2VTEN(signal_criome::schema::lib::z2VShF),
    z2VM7k(signal_criome::schema::lib::z2VfB8),
    z2VT7m(signal_criome::schema::lib::z2Vb3U),
    z2Vc6v(signal_criome::schema::lib::z2VfB8),
    z2VVxR(z2VTax),
    z2VUaf(z2VYkT),
}
pub struct z2VfCM {
    pub field_0: z2VZJL,
    pub field_1: z2VLyc,
    pub field_2: z2VZzi,
}
pub struct z2VYkT {
    pub field_0: z2VTuM,
}
pub enum z2VWc6 {z2VcGt ( z2VL6F ,) , z2VQrV ( z2VMz7 ,) , z2VRgL ( z2VP5n ,) , z2VXcc ( z2VXKH ,) ,} 
pub struct z2VMEW {}
pub struct z2VTax {
    pub field_0: z2VN7W,
}
pub struct z2VaBT(std::string::String);
impl z2VaBT {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VaaW(std::string::String);
impl z2VaaW {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VVds {
    pub field_0: z2VTuM,
    pub field_1: z2VLED,
}
pub enum z2VLyc {z2VWjv , z2VQSE , z2VRtj ,} 
pub struct z2VPDU(std::string::String);
impl z2VPDU {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VZzi(u64);
impl z2VZzi {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VYh1(std::string::String);
impl z2VYh1 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VN4g {
    pub field_0: z2VTTd,
    pub field_1: z2VLa8,
}
pub struct z2VLED {
    pub field_0: z2VLa8,
    pub field_1: z2VWc6,
}
pub struct z2VXeB {
    pub field_0: z2VZJL,
    pub field_1: z2VWZH,
    pub field_2: z2VRQk,
}
pub struct z2VRQk(std::string::String);
impl z2VRQk {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2Vdss {
    pub field_0: z2VZJL,
    pub field_1: z2VLa8,
    pub field_2: z2VZzi,
}
pub struct z2VMYt(std::string::String);
impl z2VMYt {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VRtL {
    pub field_0: z2VR8u,
    pub field_1: z2VWi6,
}
pub struct z2VMz7 {
    pub field_0: z2VLa8,
    pub field_1: z2VL6F,
    pub field_2: z2VYh1,
    pub field_3: z2VPxB,
    pub field_4: z2VcUQ,
    pub field_5: z2VLkg,
}
pub struct z2VXKH {
    pub field_0: z2VcUQ,
}
pub struct z2VR8u(std::string::String);
impl z2VR8u {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VNoR {
    pub field_0: z2VRQk,
    pub field_1: z2VV8c,
}
pub struct z2VPxB {
    pub field_0: z2VMYt,
    pub field_1: z2VWi6,
}
pub struct z2VWi6(std::string::String);
impl z2VWi6 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWEF {
    pub field_0: z2VYMA,
    pub field_1: z2VPDU,
    pub field_2: z2VWZH,
    pub field_3: z2VaBT,
    pub field_4: z2VRtL,
}
