// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_criome::schema::lib::AuthorizationRequestSlot as AuthorizationRequestSlot;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedRequestIdentifier as ParkedRequestIdentifier;
#[rustfmt::skip]
pub use signal_criome::schema::lib::InterceptPolicyIdentifier as InterceptPolicyIdentifier;
#[rustfmt::skip]
pub use signal_criome::schema::lib::InterceptPolicyProposal as InterceptPolicyProposal;
#[rustfmt::skip]
pub use signal_criome::schema::lib::InterceptPolicyCancellation as InterceptPolicyCancellation;
#[rustfmt::skip]
pub use signal_criome::schema::lib::InterceptPolicy as InterceptPolicy;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ActiveInterceptPolicies as ActiveInterceptPolicies;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedRequestQuery as ParkedRequestQuery;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedRequestSnapshot as ParkedRequestSnapshot;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedRequestAnswer as ParkedRequestAnswer;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedRequestResolution as ParkedRequestResolution;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QuestionIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProposalIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionToken(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriberName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AnswerText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExplanationText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContextLabel(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContextBody(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UpdateIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentLabel(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PaneLabel(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StatusText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NotificationText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TimestampNanos(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RevisionCounter(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProposalDigest(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketPath(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ApprovalSource {
    CriomeEscalation(AuthorizationRequestSlot),
    CriomeInterception(ParkedRequestIdentifier),
    AgentQuestion,
    LocalSystemPrompt,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QuestionContext {
    pub label: ContextLabel,
    pub body: ContextBody,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct SuggestedAnswer(Option<AnswerText>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Context(Vec<QuestionContext>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QuestionProposal {
    pub source: ApprovalSource,
    pub prompt: PromptText,
    pub(crate) suggested_answer: SuggestedAnswer,
    pub explanation: ExplanationText,
    pub(crate) context: Context,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApprovalQuestion {
    pub identifier: QuestionIdentifier,
    pub proposal: QuestionProposal,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ApprovalDecision {
    ApproveSuggestedAnswer,
    Reject,
    Defer,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum CriomeAccess {
    ReadOnly,
    ReadWrite,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApprovalVerdict {
    pub question: QuestionIdentifier,
    pub decision: ApprovalDecision,
    pub answered_by: SubscriberName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AnswerProposal {
    pub question: QuestionIdentifier,
    pub body: AnswerText,
    pub authored_by: SubscriberName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InterceptPolicyObservation {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InterfaceUpdate {
    pub identifier: UpdateIdentifier,
    pub mutation: InterfaceMutation,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum InterfaceMutation {
    SetStatus(StatusText),
    PostNotification(NotificationText),
    SetPaneContent(PaneContent),
    ClearPane(PaneLabel),
    PresentApprovalQuestion(QuestionProposal),
    WithdrawApprovalQuestion(QuestionIdentifier),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PaneContent {
    pub pane: PaneLabel,
    pub body: ContextBody,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Notification(Option<NotificationText>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Panes(Vec<PaneContent>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct PendingQuestions(Vec<ApprovalQuestion>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InterfaceState {
    pub revision: RevisionCounter,
    pub status: StatusText,
    pub(crate) notification: Notification,
    pub(crate) panes: Panes,
    pub(crate) pending_questions: PendingQuestions,
    pub criome_access: CriomeAccess,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InterfaceInterest {
    FullInterfaceState,
    StatusOnly,
    Notifications,
    PendingQuestions,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InterfaceStateObservation {
    pub subscriber: SubscriberName,
    pub interest: InterfaceInterest,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectedInterfaceState {
    pub revision: RevisionCounter,
    pub projection: InterfaceProjection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InterfaceObservationOpened {
    pub token: SubscriptionToken,
    pub state: ProjectedInterfaceState,
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum InterfaceProjection {
    FullProjection(InterfaceState),
    StatusProjection(StatusText),
    NotificationProjection(Option<NotificationText>),
    PendingQuestionsProjection(PendingQuestionsView),
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl nota::NotaBodyDecode for InterfaceProjection {
    fn from_nota_body(body: &nota::NotaBody<'_>) -> Result<Self, nota::NotaDecodeError> {
        let root_objects = body.root_objects();
        if root_objects.len() == 1
            && let Some(variant) = root_objects[0].demote_to_string()
        {
            return match variant {
                "NotificationProjection" => Ok(Self::NotificationProjection(None)),
                other => {
                    Err(nota::NotaDecodeError::UnknownVariant {
                        enum_name: "InterfaceProjection",
                        variant: other.to_owned(),
                    })
                }
            };
        }
        let children = body.expect_fields("InterfaceProjection", 2)?;
        let variant = children[0]
            .demote_to_string()
            .ok_or(nota::NotaDecodeError::ExpectedAtom {
                type_name: "enum variant",
            })?;
        match variant {
            "FullProjection" => {
                Ok(
                    Self::FullProjection(
                        <InterfaceState as nota::NotaDecode>::from_nota_block(
                            &children[1],
                        )?,
                    ),
                )
            }
            "StatusProjection" => {
                Ok(
                    Self::StatusProjection(
                        <StatusText as nota::NotaDecode>::from_nota_block(&children[1])?,
                    ),
                )
            }
            "NotificationProjection" => {
                Ok(
                    Self::NotificationProjection(
                        Some(
                            <NotificationText as nota::NotaDecode>::from_nota_block(
                                &children[1],
                            )?,
                        ),
                    ),
                )
            }
            "PendingQuestionsProjection" => {
                Ok(
                    Self::PendingQuestionsProjection(
                        <PendingQuestionsView as nota::NotaDecode>::from_nota_block(
                            &children[1],
                        )?,
                    ),
                )
            }
            other => {
                Err(nota::NotaDecodeError::UnknownVariant {
                    enum_name: "InterfaceProjection",
                    variant: other.to_owned(),
                })
            }
        }
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl nota::NotaDecode for InterfaceProjection {
    fn from_nota_block(block: &nota::Block) -> Result<Self, nota::NotaDecodeError> {
        if block.demote_to_string().is_some() {
            let root_objects = std::slice::from_ref(block);
            let body = nota::NotaBody::new(root_objects);
            return <Self as nota::NotaBodyDecode>::from_nota_body(&body);
        }
        let body = nota::NotaBlock::new(block)
            .expect_body(nota::Delimiter::Parenthesis, "InterfaceProjection")?;
        <Self as nota::NotaBodyDecode>::from_nota_body(&body)
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl nota::NotaBodyEncode for InterfaceProjection {
    fn to_nota_body(&self) -> nota::NotaBodyEncoding {
        match self {
            Self::FullProjection(payload) => {
                nota::NotaBodyEncoding::new(
                    vec![
                        "FullProjection".to_owned(), nota::NotaEncode::to_nota(payload),
                    ],
                )
            }
            Self::StatusProjection(payload) => {
                nota::NotaBodyEncoding::new(
                    vec![
                        "StatusProjection".to_owned(),
                        nota::NotaEncode::to_nota(payload),
                    ],
                )
            }
            Self::NotificationProjection(payload) => {
                let mut fields = vec!["NotificationProjection".to_owned()];
                if let Some(payload) = payload {
                    fields.push(nota::NotaEncode::to_nota(payload));
                }
                nota::NotaBodyEncoding::new(fields)
            }
            Self::PendingQuestionsProjection(payload) => {
                nota::NotaBodyEncoding::new(
                    vec![
                        "PendingQuestionsProjection".to_owned(),
                        nota::NotaEncode::to_nota(payload),
                    ],
                )
            }
        }
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl nota::NotaEncode for InterfaceProjection {
    fn to_nota(&self) -> String {
        let body = <Self as nota::NotaBodyEncode>::to_nota_body(self);
        if body.fields().len() == 1 {
            body.to_nota()
        } else {
            body.to_delimited_nota(nota::Delimiter::Parenthesis)
        }
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl nota::NotaDecodeTraced for InterfaceProjection {
    fn instance_reference() -> nota::TypeReference {
        nota::TypeReference::named("InterfaceProjection")
    }
    fn from_nota_block_traced(
        block: &nota::Block,
    ) -> Result<nota::DecodedWithSchema<Self>, nota::NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            match variant {
                "NotificationProjection" => {
                    return Ok(
                        nota::DecodedWithSchema::new(
                            Self::NotificationProjection(None),
                            nota::InstanceSchema::new(
                                <Self as nota::NotaDecodeTraced>::instance_reference(),
                                nota::InstanceSchemaBody::EnumPayload(
                                    Some(
                                        Box::new(
                                            nota::InstanceSchema::new(
                                                nota::TypeReference::optional(
                                                    nota::TypeReference::named("NotificationText"),
                                                ),
                                                nota::InstanceSchemaBody::Optional(None),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    );
                }
                other => {
                    return Err(nota::NotaDecodeError::UnknownVariant {
                        enum_name: "InterfaceProjection",
                        variant: other.to_owned(),
                    });
                }
            }
        }
        let body = nota::NotaBlock::new(block)
            .expect_body(nota::Delimiter::Parenthesis, "InterfaceProjection")?;
        let children = body.expect_fields("InterfaceProjection", 2)?;
        let variant = children[0]
            .demote_to_string()
            .ok_or(nota::NotaDecodeError::ExpectedAtom {
                type_name: "enum variant",
            })?;
        match variant {
            "FullProjection" => {
                let decoded = <InterfaceState as nota::NotaDecodeTraced>::from_nota_block_traced(
                    &children[1],
                )?;
                let (payload_value, payload_schema) = decoded.into_parts();
                Ok(
                    nota::DecodedWithSchema::new(
                        Self::FullProjection(payload_value),
                        nota::InstanceSchema::new(
                            <Self as nota::NotaDecodeTraced>::instance_reference(),
                            nota::InstanceSchemaBody::EnumPayload(
                                Some(Box::new(payload_schema)),
                            ),
                        ),
                    ),
                )
            }
            "StatusProjection" => {
                let decoded = <StatusText as nota::NotaDecodeTraced>::from_nota_block_traced(
                    &children[1],
                )?;
                let (payload_value, payload_schema) = decoded.into_parts();
                Ok(
                    nota::DecodedWithSchema::new(
                        Self::StatusProjection(payload_value),
                        nota::InstanceSchema::new(
                            <Self as nota::NotaDecodeTraced>::instance_reference(),
                            nota::InstanceSchemaBody::EnumPayload(
                                Some(Box::new(payload_schema)),
                            ),
                        ),
                    ),
                )
            }
            "NotificationProjection" => {
                let leaf = <NotificationText as nota::NotaDecodeTraced>::from_nota_block_traced(
                    &children[1],
                )?;
                let (leaf_value, leaf_schema) = leaf.into_parts();
                Ok(
                    nota::DecodedWithSchema::new(
                        Self::NotificationProjection(Some(leaf_value)),
                        nota::InstanceSchema::new(
                            <Self as nota::NotaDecodeTraced>::instance_reference(),
                            nota::InstanceSchemaBody::EnumPayload(
                                Some(
                                    Box::new(
                                        nota::InstanceSchema::new(
                                            nota::TypeReference::optional(
                                                nota::TypeReference::named("NotificationText"),
                                            ),
                                            nota::InstanceSchemaBody::Optional(
                                                Some(Box::new(leaf_schema)),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                )
            }
            "PendingQuestionsProjection" => {
                let decoded = <PendingQuestionsView as nota::NotaDecodeTraced>::from_nota_block_traced(
                    &children[1],
                )?;
                let (payload_value, payload_schema) = decoded.into_parts();
                Ok(
                    nota::DecodedWithSchema::new(
                        Self::PendingQuestionsProjection(payload_value),
                        nota::InstanceSchema::new(
                            <Self as nota::NotaDecodeTraced>::instance_reference(),
                            nota::InstanceSchemaBody::EnumPayload(
                                Some(Box::new(payload_schema)),
                            ),
                        ),
                    ),
                )
            }
            other => {
                Err(nota::NotaDecodeError::UnknownVariant {
                    enum_name: "InterfaceProjection",
                    variant: other.to_owned(),
                })
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct VisibleQuestions(Vec<ApprovalQuestion>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PendingQuestionsView(VisibleQuestions);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StandardSocket(SocketPath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QuestionPresented {
    pub question: QuestionIdentifier,
    pub revision: RevisionCounter,
    pub accepted_at: TimestampNanos,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UpdateAccepted {
    pub identifier: UpdateIdentifier,
    pub revision: RevisionCounter,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct VerdictAccepted {
    pub question: QuestionIdentifier,
    pub decision: ApprovalDecision,
    pub accepted_at: TimestampNanos,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AnswerProposalAdmitted {
    pub proposal: ProposalIdentifier,
    pub question: QuestionIdentifier,
    pub digest: ProposalDigest,
    pub revision: RevisionCounter,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InterfaceObservationRetracted(SubscriptionToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RejectionReason {
    UnknownQuestion,
    QuestionAlreadyAnswered,
    MalformedRequest,
    UnknownSubscriber,
    UnsupportedMutation,
    UnauthorizedProjection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rejection(RejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MentciEvent {
    InterfaceStateChanged(ProjectedInterfaceState),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    PresentQuestion(QuestionProposal),
    PushUpdate(InterfaceUpdate),
    ObserveInterfaceState(InterfaceStateObservation),
    AnswerQuestion(ApprovalVerdict),
    ProposeEditedAnswer(AnswerProposal),
    CreateInterceptPolicy(InterceptPolicyProposal),
    ReplaceInterceptPolicy(InterceptPolicyProposal),
    CancelInterceptPolicy(InterceptPolicyCancellation),
    ListInterceptPolicies(InterceptPolicyObservation),
    FetchParkedRequests(ParkedRequestQuery),
    AnswerParkedRequest(ParkedRequestAnswer),
    RetractInterfaceObservation(SubscriptionToken),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    QuestionPresented(QuestionPresented),
    UpdateAccepted(UpdateAccepted),
    InterfaceObservationOpened(InterfaceObservationOpened),
    VerdictAccepted(VerdictAccepted),
    AnswerProposalAdmitted(AnswerProposalAdmitted),
    InterceptPolicyCreated(InterceptPolicy),
    InterceptPolicyReplaced(InterceptPolicy),
    InterceptPolicyCancelled(InterceptPolicyIdentifier),
    InterceptPoliciesListed(ActiveInterceptPolicies),
    ParkedRequestsFetched(ParkedRequestSnapshot),
    ParkedRequestAnswered(ParkedRequestResolution),
    InterfaceObservationRetracted(InterfaceObservationRetracted),
    Rejection(Rejection),
}

#[rustfmt::skip]
impl QuestionIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for QuestionIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProposalIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ProposalIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubscriptionToken {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SubscriptionToken {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubscriberName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SubscriberName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PromptText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PromptText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AnswerText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for AnswerText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ExplanationText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ExplanationText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ContextLabel {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ContextLabel {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ContextBody {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ContextBody {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UpdateIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for UpdateIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentLabel {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ComponentLabel {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PaneLabel {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PaneLabel {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StatusText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for StatusText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NotificationText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for NotificationText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TimestampNanos {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TimestampNanos {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RevisionCounter {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for RevisionCounter {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProposalDigest {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ProposalDigest {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SocketPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for SocketPath {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SuggestedAnswer {
    pub fn new(payload: Option<AnswerText>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<AnswerText> {
        &self.0
    }
    pub fn into_payload(self) -> Option<AnswerText> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<AnswerText>> for SuggestedAnswer {
    fn from(payload: Option<AnswerText>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Context {
    pub fn new(payload: Vec<QuestionContext>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<QuestionContext> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<QuestionContext> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<QuestionContext>> for Context {
    fn from(payload: Vec<QuestionContext>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Notification {
    pub fn new(payload: Option<NotificationText>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<NotificationText> {
        &self.0
    }
    pub fn into_payload(self) -> Option<NotificationText> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<NotificationText>> for Notification {
    fn from(payload: Option<NotificationText>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Panes {
    pub fn new(payload: Vec<PaneContent>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<PaneContent> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<PaneContent> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<PaneContent>> for Panes {
    fn from(payload: Vec<PaneContent>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PendingQuestions {
    pub fn new(payload: Vec<ApprovalQuestion>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ApprovalQuestion> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ApprovalQuestion> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ApprovalQuestion>> for PendingQuestions {
    fn from(payload: Vec<ApprovalQuestion>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl VisibleQuestions {
    pub fn new(payload: Vec<ApprovalQuestion>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ApprovalQuestion> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ApprovalQuestion> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ApprovalQuestion>> for VisibleQuestions {
    fn from(payload: Vec<ApprovalQuestion>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PendingQuestionsView {
    pub fn new(payload: VisibleQuestions) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &VisibleQuestions {
        &self.0
    }
    pub fn into_payload(self) -> VisibleQuestions {
        self.0
    }
}
#[rustfmt::skip]
impl From<VisibleQuestions> for PendingQuestionsView {
    fn from(payload: VisibleQuestions) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StandardSocket {
    pub fn new(payload: SocketPath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketPath {
        &self.0
    }
    pub fn into_payload(self) -> SocketPath {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketPath> for StandardSocket {
    fn from(payload: SocketPath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InterfaceObservationRetracted {
    pub fn new(payload: SubscriptionToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionToken {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionToken> for InterfaceObservationRetracted {
    fn from(payload: SubscriptionToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Rejection {
    pub fn new(payload: RejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> RejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectionReason> for Rejection {
    fn from(payload: RejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ApprovalSource {
    pub fn criome_escalation(payload: AuthorizationRequestSlot) -> Self {
        Self::CriomeEscalation(payload)
    }
    pub fn criome_interception(payload: ParkedRequestIdentifier) -> Self {
        Self::CriomeInterception(payload)
    }
}

#[rustfmt::skip]
impl InterfaceMutation {
    pub fn set_status(payload: String) -> Self {
        Self::SetStatus(StatusText::new(payload))
    }
    pub fn post_notification(payload: String) -> Self {
        Self::PostNotification(NotificationText::new(payload))
    }
    pub fn set_pane_content(payload: PaneContent) -> Self {
        Self::SetPaneContent(payload)
    }
    pub fn clear_pane(payload: String) -> Self {
        Self::ClearPane(PaneLabel::new(payload))
    }
    pub fn present_approval_question(payload: QuestionProposal) -> Self {
        Self::PresentApprovalQuestion(payload)
    }
    pub fn withdraw_approval_question(payload: String) -> Self {
        Self::WithdrawApprovalQuestion(QuestionIdentifier::new(payload))
    }
}

#[rustfmt::skip]
impl InterfaceProjection {
    pub fn full_projection(payload: InterfaceState) -> Self {
        Self::FullProjection(payload)
    }
    pub fn status_projection(payload: String) -> Self {
        Self::StatusProjection(StatusText::new(payload))
    }
    pub fn notification_projection(payload: Option<NotificationText>) -> Self {
        Self::NotificationProjection(payload)
    }
    pub fn pending_questions_projection(payload: VisibleQuestions) -> Self {
        Self::PendingQuestionsProjection(PendingQuestionsView::new(payload))
    }
}

#[rustfmt::skip]
impl MentciEvent {
    pub fn interface_state_changed(payload: ProjectedInterfaceState) -> Self {
        Self::InterfaceStateChanged(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn present_question(payload: QuestionProposal) -> Self {
        Self::PresentQuestion(payload)
    }
    pub fn push_update(payload: InterfaceUpdate) -> Self {
        Self::PushUpdate(payload)
    }
    pub fn observe_interface_state(payload: InterfaceStateObservation) -> Self {
        Self::ObserveInterfaceState(payload)
    }
    pub fn answer_question(payload: ApprovalVerdict) -> Self {
        Self::AnswerQuestion(payload)
    }
    pub fn propose_edited_answer(payload: AnswerProposal) -> Self {
        Self::ProposeEditedAnswer(payload)
    }
    pub fn create_intercept_policy(payload: InterceptPolicyProposal) -> Self {
        Self::CreateInterceptPolicy(payload)
    }
    pub fn replace_intercept_policy(payload: InterceptPolicyProposal) -> Self {
        Self::ReplaceInterceptPolicy(payload)
    }
    pub fn cancel_intercept_policy(payload: InterceptPolicyCancellation) -> Self {
        Self::CancelInterceptPolicy(payload)
    }
    pub fn list_intercept_policies(payload: InterceptPolicyObservation) -> Self {
        Self::ListInterceptPolicies(payload)
    }
    pub fn fetch_parked_requests(payload: ParkedRequestQuery) -> Self {
        Self::FetchParkedRequests(payload)
    }
    pub fn answer_parked_request(payload: ParkedRequestAnswer) -> Self {
        Self::AnswerParkedRequest(payload)
    }
    pub fn retract_interface_observation(payload: String) -> Self {
        Self::RetractInterfaceObservation(SubscriptionToken::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn question_presented(payload: QuestionPresented) -> Self {
        Self::QuestionPresented(payload)
    }
    pub fn update_accepted(payload: UpdateAccepted) -> Self {
        Self::UpdateAccepted(payload)
    }
    pub fn interface_observation_opened(payload: InterfaceObservationOpened) -> Self {
        Self::InterfaceObservationOpened(payload)
    }
    pub fn verdict_accepted(payload: VerdictAccepted) -> Self {
        Self::VerdictAccepted(payload)
    }
    pub fn answer_proposal_admitted(payload: AnswerProposalAdmitted) -> Self {
        Self::AnswerProposalAdmitted(payload)
    }
    pub fn intercept_policy_created(payload: InterceptPolicy) -> Self {
        Self::InterceptPolicyCreated(payload)
    }
    pub fn intercept_policy_replaced(payload: InterceptPolicy) -> Self {
        Self::InterceptPolicyReplaced(payload)
    }
    pub fn intercept_policy_cancelled(payload: InterceptPolicyIdentifier) -> Self {
        Self::InterceptPolicyCancelled(payload)
    }
    pub fn intercept_policies_listed(payload: ActiveInterceptPolicies) -> Self {
        Self::InterceptPoliciesListed(payload)
    }
    pub fn parked_requests_fetched(payload: ParkedRequestSnapshot) -> Self {
        Self::ParkedRequestsFetched(payload)
    }
    pub fn parked_request_answered(payload: ParkedRequestResolution) -> Self {
        Self::ParkedRequestAnswered(payload)
    }
    pub fn interface_observation_retracted(payload: SubscriptionToken) -> Self {
        Self::InterfaceObservationRetracted(InterfaceObservationRetracted::new(payload))
    }
    pub fn rejection(payload: RejectionReason) -> Self {
        Self::Rejection(Rejection::new(payload))
    }
}

#[rustfmt::skip]
impl From<AuthorizationRequestSlot> for ApprovalSource {
    fn from(payload: AuthorizationRequestSlot) -> Self {
        Self::CriomeEscalation(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedRequestIdentifier> for ApprovalSource {
    fn from(payload: ParkedRequestIdentifier) -> Self {
        Self::CriomeInterception(payload)
    }
}

#[rustfmt::skip]
impl From<StatusText> for InterfaceMutation {
    fn from(payload: StatusText) -> Self {
        Self::SetStatus(payload)
    }
}

#[rustfmt::skip]
impl From<NotificationText> for InterfaceMutation {
    fn from(payload: NotificationText) -> Self {
        Self::PostNotification(payload)
    }
}

#[rustfmt::skip]
impl From<PaneContent> for InterfaceMutation {
    fn from(payload: PaneContent) -> Self {
        Self::SetPaneContent(payload)
    }
}

#[rustfmt::skip]
impl From<PaneLabel> for InterfaceMutation {
    fn from(payload: PaneLabel) -> Self {
        Self::ClearPane(payload)
    }
}

#[rustfmt::skip]
impl From<QuestionProposal> for InterfaceMutation {
    fn from(payload: QuestionProposal) -> Self {
        Self::PresentApprovalQuestion(payload)
    }
}

#[rustfmt::skip]
impl From<QuestionIdentifier> for InterfaceMutation {
    fn from(payload: QuestionIdentifier) -> Self {
        Self::WithdrawApprovalQuestion(payload)
    }
}

#[rustfmt::skip]
impl From<InterfaceState> for InterfaceProjection {
    fn from(payload: InterfaceState) -> Self {
        Self::FullProjection(payload)
    }
}

#[rustfmt::skip]
impl From<StatusText> for InterfaceProjection {
    fn from(payload: StatusText) -> Self {
        Self::StatusProjection(payload)
    }
}

#[rustfmt::skip]
impl From<PendingQuestionsView> for InterfaceProjection {
    fn from(payload: PendingQuestionsView) -> Self {
        Self::PendingQuestionsProjection(payload)
    }
}

#[rustfmt::skip]
impl From<ProjectedInterfaceState> for MentciEvent {
    fn from(payload: ProjectedInterfaceState) -> Self {
        Self::InterfaceStateChanged(payload)
    }
}

#[rustfmt::skip]
impl From<QuestionProposal> for Input {
    fn from(payload: QuestionProposal) -> Self {
        Self::PresentQuestion(payload)
    }
}

#[rustfmt::skip]
impl From<InterfaceUpdate> for Input {
    fn from(payload: InterfaceUpdate) -> Self {
        Self::PushUpdate(payload)
    }
}

#[rustfmt::skip]
impl From<InterfaceStateObservation> for Input {
    fn from(payload: InterfaceStateObservation) -> Self {
        Self::ObserveInterfaceState(payload)
    }
}

#[rustfmt::skip]
impl From<ApprovalVerdict> for Input {
    fn from(payload: ApprovalVerdict) -> Self {
        Self::AnswerQuestion(payload)
    }
}

#[rustfmt::skip]
impl From<AnswerProposal> for Input {
    fn from(payload: AnswerProposal) -> Self {
        Self::ProposeEditedAnswer(payload)
    }
}

#[rustfmt::skip]
impl From<InterceptPolicyCancellation> for Input {
    fn from(payload: InterceptPolicyCancellation) -> Self {
        Self::CancelInterceptPolicy(payload)
    }
}

#[rustfmt::skip]
impl From<InterceptPolicyObservation> for Input {
    fn from(payload: InterceptPolicyObservation) -> Self {
        Self::ListInterceptPolicies(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedRequestQuery> for Input {
    fn from(payload: ParkedRequestQuery) -> Self {
        Self::FetchParkedRequests(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedRequestAnswer> for Input {
    fn from(payload: ParkedRequestAnswer) -> Self {
        Self::AnswerParkedRequest(payload)
    }
}

#[rustfmt::skip]
impl From<SubscriptionToken> for Input {
    fn from(payload: SubscriptionToken) -> Self {
        Self::RetractInterfaceObservation(payload)
    }
}

#[rustfmt::skip]
impl From<QuestionPresented> for Output {
    fn from(payload: QuestionPresented) -> Self {
        Self::QuestionPresented(payload)
    }
}

#[rustfmt::skip]
impl From<UpdateAccepted> for Output {
    fn from(payload: UpdateAccepted) -> Self {
        Self::UpdateAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<InterfaceObservationOpened> for Output {
    fn from(payload: InterfaceObservationOpened) -> Self {
        Self::InterfaceObservationOpened(payload)
    }
}

#[rustfmt::skip]
impl From<VerdictAccepted> for Output {
    fn from(payload: VerdictAccepted) -> Self {
        Self::VerdictAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<AnswerProposalAdmitted> for Output {
    fn from(payload: AnswerProposalAdmitted) -> Self {
        Self::AnswerProposalAdmitted(payload)
    }
}

#[rustfmt::skip]
impl From<InterceptPolicyIdentifier> for Output {
    fn from(payload: InterceptPolicyIdentifier) -> Self {
        Self::InterceptPolicyCancelled(payload)
    }
}

#[rustfmt::skip]
impl From<ActiveInterceptPolicies> for Output {
    fn from(payload: ActiveInterceptPolicies) -> Self {
        Self::InterceptPoliciesListed(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedRequestSnapshot> for Output {
    fn from(payload: ParkedRequestSnapshot) -> Self {
        Self::ParkedRequestsFetched(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedRequestResolution> for Output {
    fn from(payload: ParkedRequestResolution) -> Self {
        Self::ParkedRequestAnswered(payload)
    }
}

#[rustfmt::skip]
impl From<InterfaceObservationRetracted> for Output {
    fn from(payload: InterfaceObservationRetracted) -> Self {
        Self::InterfaceObservationRetracted(payload)
    }
}

#[rustfmt::skip]
impl From<Rejection> for Output {
    fn from(payload: Rejection) -> Self {
        Self::Rejection(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_PRESENT_QUESTION: u64 = 0x0000000000000000;
    pub const INPUT_PUSH_UPDATE: u64 = 0x0001000000000000;
    pub const INPUT_OBSERVE_INTERFACE_STATE: u64 = 0x0002000000000000;
    pub const INPUT_ANSWER_QUESTION: u64 = 0x0003000000000000;
    pub const INPUT_PROPOSE_EDITED_ANSWER: u64 = 0x0004000000000000;
    pub const INPUT_CREATE_INTERCEPT_POLICY: u64 = 0x0005000000000000;
    pub const INPUT_REPLACE_INTERCEPT_POLICY: u64 = 0x0006000000000000;
    pub const INPUT_CANCEL_INTERCEPT_POLICY: u64 = 0x0007000000000000;
    pub const INPUT_LIST_INTERCEPT_POLICIES: u64 = 0x0008000000000000;
    pub const INPUT_FETCH_PARKED_REQUESTS: u64 = 0x0009000000000000;
    pub const INPUT_ANSWER_PARKED_REQUEST: u64 = 0x000A000000000000;
    pub const INPUT_RETRACT_INTERFACE_OBSERVATION: u64 = 0x000B000000000000;
    pub const OUTPUT_QUESTION_PRESENTED: u64 = 0x0100000000000000;
    pub const OUTPUT_UPDATE_ACCEPTED: u64 = 0x0101000000000000;
    pub const OUTPUT_INTERFACE_OBSERVATION_OPENED: u64 = 0x0102000000000000;
    pub const OUTPUT_VERDICT_ACCEPTED: u64 = 0x0103000000000000;
    pub const OUTPUT_ANSWER_PROPOSAL_ADMITTED: u64 = 0x0104000000000000;
    pub const OUTPUT_INTERCEPT_POLICY_CREATED: u64 = 0x0105000000000000;
    pub const OUTPUT_INTERCEPT_POLICY_REPLACED: u64 = 0x0106000000000000;
    pub const OUTPUT_INTERCEPT_POLICY_CANCELLED: u64 = 0x0107000000000000;
    pub const OUTPUT_INTERCEPT_POLICIES_LISTED: u64 = 0x0108000000000000;
    pub const OUTPUT_PARKED_REQUESTS_FETCHED: u64 = 0x0109000000000000;
    pub const OUTPUT_PARKED_REQUEST_ANSWERED: u64 = 0x010A000000000000;
    pub const OUTPUT_INTERFACE_OBSERVATION_RETRACTED: u64 = 0x010B000000000000;
    pub const OUTPUT_REJECTION: u64 = 0x010C000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    PresentQuestion,
    PushUpdate,
    ObserveInterfaceState,
    AnswerQuestion,
    ProposeEditedAnswer,
    CreateInterceptPolicy,
    ReplaceInterceptPolicy,
    CancelInterceptPolicy,
    ListInterceptPolicies,
    FetchParkedRequests,
    AnswerParkedRequest,
    RetractInterfaceObservation,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    QuestionPresented,
    UpdateAccepted,
    InterfaceObservationOpened,
    VerdictAccepted,
    AnswerProposalAdmitted,
    InterceptPolicyCreated,
    InterceptPolicyReplaced,
    InterceptPolicyCancelled,
    InterceptPoliciesListed,
    ParkedRequestsFetched,
    ParkedRequestAnswered,
    InterfaceObservationRetracted,
    Rejection,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::PresentQuestion(_) => InputRoute::PresentQuestion,
            Self::PushUpdate(_) => InputRoute::PushUpdate,
            Self::ObserveInterfaceState(_) => InputRoute::ObserveInterfaceState,
            Self::AnswerQuestion(_) => InputRoute::AnswerQuestion,
            Self::ProposeEditedAnswer(_) => InputRoute::ProposeEditedAnswer,
            Self::CreateInterceptPolicy(_) => InputRoute::CreateInterceptPolicy,
            Self::ReplaceInterceptPolicy(_) => InputRoute::ReplaceInterceptPolicy,
            Self::CancelInterceptPolicy(_) => InputRoute::CancelInterceptPolicy,
            Self::ListInterceptPolicies(_) => InputRoute::ListInterceptPolicies,
            Self::FetchParkedRequests(_) => InputRoute::FetchParkedRequests,
            Self::AnswerParkedRequest(_) => InputRoute::AnswerParkedRequest,
            Self::RetractInterfaceObservation(_) => {
                InputRoute::RetractInterfaceObservation
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::PresentQuestion(_) => short_header::INPUT_PRESENT_QUESTION,
            Self::PushUpdate(_) => short_header::INPUT_PUSH_UPDATE,
            Self::ObserveInterfaceState(_) => short_header::INPUT_OBSERVE_INTERFACE_STATE,
            Self::AnswerQuestion(_) => short_header::INPUT_ANSWER_QUESTION,
            Self::ProposeEditedAnswer(_) => short_header::INPUT_PROPOSE_EDITED_ANSWER,
            Self::CreateInterceptPolicy(_) => short_header::INPUT_CREATE_INTERCEPT_POLICY,
            Self::ReplaceInterceptPolicy(_) => {
                short_header::INPUT_REPLACE_INTERCEPT_POLICY
            }
            Self::CancelInterceptPolicy(_) => short_header::INPUT_CANCEL_INTERCEPT_POLICY,
            Self::ListInterceptPolicies(_) => short_header::INPUT_LIST_INTERCEPT_POLICIES,
            Self::FetchParkedRequests(_) => short_header::INPUT_FETCH_PARKED_REQUESTS,
            Self::AnswerParkedRequest(_) => short_header::INPUT_ANSWER_PARKED_REQUEST,
            Self::RetractInterfaceObservation(_) => {
                short_header::INPUT_RETRACT_INTERFACE_OBSERVATION
            }
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_PRESENT_QUESTION => Ok(InputRoute::PresentQuestion),
            short_header::INPUT_PUSH_UPDATE => Ok(InputRoute::PushUpdate),
            short_header::INPUT_OBSERVE_INTERFACE_STATE => {
                Ok(InputRoute::ObserveInterfaceState)
            }
            short_header::INPUT_ANSWER_QUESTION => Ok(InputRoute::AnswerQuestion),
            short_header::INPUT_PROPOSE_EDITED_ANSWER => {
                Ok(InputRoute::ProposeEditedAnswer)
            }
            short_header::INPUT_CREATE_INTERCEPT_POLICY => {
                Ok(InputRoute::CreateInterceptPolicy)
            }
            short_header::INPUT_REPLACE_INTERCEPT_POLICY => {
                Ok(InputRoute::ReplaceInterceptPolicy)
            }
            short_header::INPUT_CANCEL_INTERCEPT_POLICY => {
                Ok(InputRoute::CancelInterceptPolicy)
            }
            short_header::INPUT_LIST_INTERCEPT_POLICIES => {
                Ok(InputRoute::ListInterceptPolicies)
            }
            short_header::INPUT_FETCH_PARKED_REQUESTS => {
                Ok(InputRoute::FetchParkedRequests)
            }
            short_header::INPUT_ANSWER_PARKED_REQUEST => {
                Ok(InputRoute::AnswerParkedRequest)
            }
            short_header::INPUT_RETRACT_INTERFACE_OBSERVATION => {
                Ok(InputRoute::RetractInterfaceObservation)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::QuestionPresented(_) => OutputRoute::QuestionPresented,
            Self::UpdateAccepted(_) => OutputRoute::UpdateAccepted,
            Self::InterfaceObservationOpened(_) => {
                OutputRoute::InterfaceObservationOpened
            }
            Self::VerdictAccepted(_) => OutputRoute::VerdictAccepted,
            Self::AnswerProposalAdmitted(_) => OutputRoute::AnswerProposalAdmitted,
            Self::InterceptPolicyCreated(_) => OutputRoute::InterceptPolicyCreated,
            Self::InterceptPolicyReplaced(_) => OutputRoute::InterceptPolicyReplaced,
            Self::InterceptPolicyCancelled(_) => OutputRoute::InterceptPolicyCancelled,
            Self::InterceptPoliciesListed(_) => OutputRoute::InterceptPoliciesListed,
            Self::ParkedRequestsFetched(_) => OutputRoute::ParkedRequestsFetched,
            Self::ParkedRequestAnswered(_) => OutputRoute::ParkedRequestAnswered,
            Self::InterfaceObservationRetracted(_) => {
                OutputRoute::InterfaceObservationRetracted
            }
            Self::Rejection(_) => OutputRoute::Rejection,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::QuestionPresented(_) => short_header::OUTPUT_QUESTION_PRESENTED,
            Self::UpdateAccepted(_) => short_header::OUTPUT_UPDATE_ACCEPTED,
            Self::InterfaceObservationOpened(_) => {
                short_header::OUTPUT_INTERFACE_OBSERVATION_OPENED
            }
            Self::VerdictAccepted(_) => short_header::OUTPUT_VERDICT_ACCEPTED,
            Self::AnswerProposalAdmitted(_) => {
                short_header::OUTPUT_ANSWER_PROPOSAL_ADMITTED
            }
            Self::InterceptPolicyCreated(_) => {
                short_header::OUTPUT_INTERCEPT_POLICY_CREATED
            }
            Self::InterceptPolicyReplaced(_) => {
                short_header::OUTPUT_INTERCEPT_POLICY_REPLACED
            }
            Self::InterceptPolicyCancelled(_) => {
                short_header::OUTPUT_INTERCEPT_POLICY_CANCELLED
            }
            Self::InterceptPoliciesListed(_) => {
                short_header::OUTPUT_INTERCEPT_POLICIES_LISTED
            }
            Self::ParkedRequestsFetched(_) => {
                short_header::OUTPUT_PARKED_REQUESTS_FETCHED
            }
            Self::ParkedRequestAnswered(_) => {
                short_header::OUTPUT_PARKED_REQUEST_ANSWERED
            }
            Self::InterfaceObservationRetracted(_) => {
                short_header::OUTPUT_INTERFACE_OBSERVATION_RETRACTED
            }
            Self::Rejection(_) => short_header::OUTPUT_REJECTION,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_QUESTION_PRESENTED => Ok(OutputRoute::QuestionPresented),
            short_header::OUTPUT_UPDATE_ACCEPTED => Ok(OutputRoute::UpdateAccepted),
            short_header::OUTPUT_INTERFACE_OBSERVATION_OPENED => {
                Ok(OutputRoute::InterfaceObservationOpened)
            }
            short_header::OUTPUT_VERDICT_ACCEPTED => Ok(OutputRoute::VerdictAccepted),
            short_header::OUTPUT_ANSWER_PROPOSAL_ADMITTED => {
                Ok(OutputRoute::AnswerProposalAdmitted)
            }
            short_header::OUTPUT_INTERCEPT_POLICY_CREATED => {
                Ok(OutputRoute::InterceptPolicyCreated)
            }
            short_header::OUTPUT_INTERCEPT_POLICY_REPLACED => {
                Ok(OutputRoute::InterceptPolicyReplaced)
            }
            short_header::OUTPUT_INTERCEPT_POLICY_CANCELLED => {
                Ok(OutputRoute::InterceptPolicyCancelled)
            }
            short_header::OUTPUT_INTERCEPT_POLICIES_LISTED => {
                Ok(OutputRoute::InterceptPoliciesListed)
            }
            short_header::OUTPUT_PARKED_REQUESTS_FETCHED => {
                Ok(OutputRoute::ParkedRequestsFetched)
            }
            short_header::OUTPUT_PARKED_REQUEST_ANSWERED => {
                Ok(OutputRoute::ParkedRequestAnswered)
            }
            short_header::OUTPUT_INTERFACE_OBSERVATION_RETRACTED => {
                Ok(OutputRoute::InterfaceObservationRetracted)
            }
            short_header::OUTPUT_REJECTION => Ok(OutputRoute::Rejection),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "PresentQuestion",
        "PushUpdate",
        "ObserveInterfaceState",
        "AnswerQuestion",
        "ProposeEditedAnswer",
        "CreateInterceptPolicy",
        "ReplaceInterceptPolicy",
        "CancelInterceptPolicy",
        "ListInterceptPolicies",
        "FetchParkedRequests",
        "AnswerParkedRequest",
        "RetractInterfaceObservation",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
